### ISSUE TITLE
Nonsymmetrical GUI

### ISSUE THREAD

**Issue by variety754** [Khajiitos/ServerCountryFlags#3]
![image](https://user-images.githubusercontent.com/124847943/229671559-1f54ea8b-b719-4ecc-84ff-9b7e4ae8e869.png)

On GUI scale 4 button for viewing server location on map is out of borders and it looks not as good as it could look

**Comment by Khajiitos** [comment]
Hi, thanks for creating an issue for this! The reason that's happening is likely because a mod, although I might be wrong. If I had to guess, it's likely the mod that adds these two buttons at the top of the screen. Could you provide the name of that mod, so that I can find an approach that works with it too?

**Comment by variety754** [comment]
Server Browser (https://www.curseforge.com/minecraft/mc-mods/server-browser)
and
Proxy (https://www.curseforge.com/minecraft/mc-mods/proxy-server)

**Comment by Khajiitos** [comment]
Actually it's none of these mods' fault, it's just that they slightly changed the position of the buttons since 1.19.4...
Mojang really started to hate modders since 1.19
But I'm working on fixing that!

**Comment by variety754** [comment]
Cool! Thank you for that, I really appreciate the effort you put in this mod

**Comment by variety754** [comment]
In new version position is ok, thanks for fox

**Comment by Khajiitos** [comment]
I'm glad it fixed it! As always, if you notice any other problems, please let me know!
