### ISSUE TITLE
[Bug] Does not support SRV

### ISSUE THREAD

**Issue by Finoway** [Khajiitos/ServerCountryFlags#8]
Hello,

I realised that the ServerCountryFlags mod doesn't support SRV DNS, so either we have the ip flag in type A or CNAME and if there is no A or CNAME we get a "?".

Example on minehut with the domain minehut.gg which has no type A or CNAME.

Here are the DNS informations for minehut.gg which uses an SRV type: 
![image](https://github.com/Khajiitos/ServerCountryFlags/assets/48923336/de0a511c-2a73-4837-9927-143df46a17b3) 
![image](https://github.com/Khajiitos/ServerCountryFlags/assets/48923336/d2836e8e-bdd7-4f32-923d-49991d5a61e5) 
![image](https://github.com/Khajiitos/ServerCountryFlags/assets/48923336/c6601a66-4103-4646-9ede-64776e94379f)

Here is an example in the list of servers: 
![image](https://github.com/Khajiitos/ServerCountryFlags/assets/48923336/c581670b-534d-40c4-b7ae-2bbb1aa4fedb)

**Comment by Khajiitos** [comment]
Hi, thanks for reporting this issue! The mod does resolve SRV DNS, but only if it resolved the hostname from A/CNAME first.
minehut.gg is a special case which has a SRV record and no other records, which I haven't considered.
If the hostname has a SRV record, the mod will ignore what it had resolved previously, so that is definitely a bug.
I will fix this in an upcoming version, thanks!
![image](https://github.com/Khajiitos/ServerCountryFlags/assets/58109276/d8e1da89-c576-437b-bc24-8feb67eb81e3)

**Comment by Khajiitos** [comment]
This issue should now be fixed in version 1.7.2, which will be available to download shortly (1.20.x only for now). Thanks!
